[package]
name = "mio_server"
version = "0.1.1"
authors = ["Jhonattan <jma9974@gmail.com>"]
description = "Simple RTMP server utilizing mio"

[dependencies]
mio = "0.6.13"
slab = "0.4.0"
bytes = "0.5"
rml_rtmp = {path="../rml_rtmp"}
clap = {version = "2.31", features = ["yaml"]}